### ISSUE TITLE
Dúvidas sobre rotas

### ISSUE THREAD

**Issue by toledompm** [jasondavindev/fatec-blog#14]
Queria saber se não tem como nós deixarmos as rotas mais legiveis, por exemplo ao invés de `/posts/user/{userId}` poderiamos colocar algo como `/{username}/posts`. Tentei dar uma fuçada e até consegui, mas ficou meio gambeta, ai queria sua opinião sobre o assunto antes de aprofundar mais.

**Comment by jasondavindev** [comment]
Sim, isso é possível. Mas seguindos os padrões REST, posts pertencem a um usuário.
Poderíamos criar um `/users/{username}/posts` pra retornar os posts ou um `/posts?userId=param`.
A primeira abordagem é boa, mas não é bom ficar aninhando recursos nas rotas. A segunda abordagem resolve rotas aninhadas, porém é menos elegante, então tem esse trade-off.
